#include "actionmap.h"
#include "action_code.h"
#include "actionmap_common.h"

/* SCAFPAD-30 - Version 1.0 - ben@buttonpusher.tv */
/*
 * Actions
 */
#define AC_SCAF01    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F1)
#define AC_SCAF02    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F2)
#define AC_SCAF03    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F3)
#define AC_SCAF04    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F4)
#define AC_SCAF05    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F5)
#define AC_SCAF06    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F6)
#define AC_SCAF07    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F7)
#define AC_SCAF08    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F8)
#define AC_SCAF09    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F9)
#define AC_SCAF10    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F10)
#define AC_SCAF11    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F11)
#define AC_SCAF12    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F12)
#define AC_SCAF13    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F13)
#define AC_SCAF14    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F14)
#define AC_SCAF15    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F15)
#define AC_SCAF16    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F16)
#define AC_SCAF17    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F17)
#define AC_SCAF18    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F18)
#define AC_SCAF19    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F19)
#define AC_SCAF20    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F20)
#define AC_SCAF21    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F21)
#define AC_SCAF22    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F22)
#define AC_SCAF23    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F23)
#define AC_SCAF24    ACTION_MODS_KEY(MOD_LSFT | MOD_LALT | MOD_LCTL, KC_F24)

const action_t PROGMEM actionmaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = ACTIONMAP( \
      SCAF01,SCAF02,SCAF03,SCAF04,SCAF05,SCAF06,SCAF07,SCAF08,SCAF09,SCAF10, \
      SCAF11,SCAF12,SCAF13,SCAF14,SCAF15,SCAF16,SCAF17,SCAF18,SCAF19,SCAF20, \
      J,K,L,V,A,Z,SCAF21,SCAF22,SCAF23,SCAF24),
};
